language: go

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

install:
  - |
    if [ ! -d /home/travis/gopath/src/github.com/ncr-devops-platform ]; then
      mv /home/travis/gopath/src/github.com/* /home/travis/gopath/src/github.com/ncr-devops-platform
    fi
  - git checkout .
  - ./godelw version
  - ./godelw project-version

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./... && bash <(curl -s https://codecov.io/bash)
  - make clean
  - make package
  - scripts/validate-version.sh

deploy:
  provider: releases
  api_key:
    secure: V31VHHJF+4yzDrsouJ65iEuaUJL6ZweYnb0sCDKUn3BEjot5otLzXmfOxSaDY1GsVvUxdjfQqBhdTGmXc9qxj6dCrc6wN3lnA/gD8cx+X7SX4r+lvh5xgFzjTwS9iEAj0DhIxBWZPApfcDzi4Ie8lslHwAQ0kaKACFacWZJC6dASbk9anE9z7f0pNi1Rvr7rtcemtW6mJmdA9oo8E01csn1YnfXhtKRLHXiJZgifhTrUowIOTK/qS+XwniWqwbo8ebX26cVcwOXRnuvB7ixdx6uF/JsGekPElLDiFwVYmz9Yv3QN/bfBY0Q/EAGbdnqTPCe6DOe6mxD3Ai3Drk8zxGjCa70jUPVXzQ6TyZ5Dkkul2unUnE3Ffb++SmQUArNO4ARgnl29AsVOmZiwPBEe43RhN37oVan1Ln9FWMmN8pURzlqW3knQAM8KJAhLredtK08se3EMtzrOVLwFZIrMGf9bUA5wDkEIZqsCzdXWbXfOqql7zL4MyFVpr/MZM+yatt0Xjc8WsoiOqEo7tf03bzubAJLLdesbC/q2APKjOK1L8S7ZXaGzEDbb34Yv07mXlz1AtPYWjrqZ5yrfRKJwcA1BSNdhi5ZRogXOtsMMz0hRii5O/6gNL3qhShMoL3ya4ZqZ+dtb0McLGNlqlgbtoCPlYVWc3uZeIdn/KeiEiwc=
  file_glob: true
  file: out/package/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
