products:
  check_available_memory:
    build:
      main-pkg: 'cmd/check_available_memory'
      build-args-script: |
        echo "-ldflags"
        echo -n "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdName=check_available_memory "
        echo "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdVersion=$(./godelw project-version)"
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_cpu:
    build:
      main-pkg: 'cmd/check_cpu'
      build-args-script: |
        echo "-ldflags"
        echo -n "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdName=check_cpu "
        echo "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdVersion=$(./godelw project-version)"
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_performance_counter:
    build:
      main-pkg: 'cmd/check_performance_counter'
      build-args-script: |
        echo "-ldflags"
        echo -n "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdName=check_performance_counter "
        echo "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdVersion=$(./godelw project-version)"
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_service:
    build:
      main-pkg: 'cmd/check_service'
      build-args-script: |
        echo "-ldflags"
        echo -n "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdName=check_service "
        echo "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdVersion=$(./godelw project-version)"
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_user_group:
    build:
      main-pkg: 'cmd/check_user_group'
      build-args-script: |
        echo "-ldflags"
        echo -n "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdName=check_user_group "
        echo "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdVersion=$(./godelw project-version)"
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_process:
    build:
      main-pkg: 'cmd/check_process'
      build-args-script: |
        echo "-ldflags"
        echo -n "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdName=check_process "
        echo "-X github.com/ncr-devops-platform/nagiosfoundation/lib/app/nagiosfoundation.cmdVersion=$(./godelw project-version)"
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
