products:
  check_memory:
    build:
      main-pkg: 'cmd/check_memory'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_cpu:
    build:
      main-pkg: 'cmd/check_cpu'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_file_exists:
    build:
      main-pkg: 'cmd/check_file_exists'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_performance_counter:
    build:
      main-pkg: 'cmd/check_performance_counter'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_service:
    build:
      main-pkg: 'cmd/check_service'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_user_group:
    build:
      main-pkg: 'cmd/check_user_group'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_process:
    build:
      main-pkg: 'cmd/check_process'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
  check_http:
    build:
      main-pkg: 'cmd/check_http'
      build-args-script: scripts/inject-name-version.sh
      os-archs:
        - os: windows
          arch: amd64
        - os: windows
          arch: "386"
        - os: linux
          arch: amd64
        - os: linux
          arch: "386"
    dist:
        disters:
          type: os-arch-bin
          config:
            os-archs:
              - os: windows
                arch: amd64
